import React from "react";
import Header from "../Header";
import Head from "next/head";

type Props = any;

const PageWrapper = ({ children, wrapperCss = "" }: Props) => {
  return (
    <div
      className={`bg-bg-primary min-h-screen relative text-white ${wrapperCss}`}>
      <Head>
        <title>Chinmaya's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
    </div>
  );
};

export default PageWrapper;
